# Generated by Django 4.2.15 on 2025-04-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book'), ('can_edit', 'Can edit book'), ('can_delete', 'Can delete book'), ('can_create', 'Can create book')]},
        ),
    ]
